//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROYECTO_1.BASE
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public int ID_S { get; set; }
        public Nullable<int> ID_C { get; set; }
        public string TIPO { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public Nullable<double> PRECIO { get; set; }
        public Nullable<double> TOTAL { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
